vich_uploader:
    db_driver: orm

    mappings:
       colleagues:
           uri_prefix: /images/colleagues
           upload_destination: '%kernel.project_dir%/public/images/colleagues'
           inject_on_load:     false
           delete_on_update:   true
           delete_on_remove:   true
